# Generated by Django 2.1.7 on 2019-10-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_projectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='complete',
            field=models.BooleanField(null=True),
        ),
    ]
