# Generated by Django 2.1.7 on 2019-10-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bucketlist_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='complete',
            field=models.BooleanField(default='No', null=True),
        ),
    ]
