# Generated by Django 2.1.7 on 2019-10-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191019_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
