# Generated by Django 2.1.7 on 2019-10-05 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='date',
            new_name='completed_date',
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='title',
            new_name='to_do',
        ),
    ]
